# This is a basic workflow to build robot code and use spotless formatting.

name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and run tests on robot code
      run: ./gradlew build
    - name: Spotlesss Check
      run: ./gradlew spotlessCheck
